services:
  web:
    build: .
    command: sh -c "
        python manage.py migrate && 
        apt-get update -y &&
        apt-get upgrade -y &&
        apt-get install cron -y && 
        python manage.py crontab add && 
        python manage.py runserver 0.0.0.0:3000 &&
        service cron start
      "
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      
