# Generated by Django 5.1.6 on 2025-07-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alert_threshold',
            },
        ),
        migrations.CreateModel(
            name='RefIndicator',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ref_indicator',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(choices=[('auto', 'Automatique'), ('admin', 'Administrateur')], max_length=16)),
                ('value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField()),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.alertthreshold')),
            ],
            options={
                'db_table': 'alerte',
            },
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refindicator'),
        ),
    ]
