# Generated by Django 5.1.6 on 2025-07-07 06:29

from django.db import migrations

def seed_indicators(apps, schema_editor):
    RefIndicator = apps.get_model('api', 'RefIndicator')
    data = [
        {"code": "aqi", "label": "Indice Qualité de l'Air", "description": "Indice global de pollution OWM."},
        {"code": "co", "label": "Monoxyde de carbone", "description": "CO."},
        {"code": "no", "label": "Monoxyde d’azote", "description": "NO."},
        {"code": "no2", "label": "Dioxyde d’azote", "description": "NO2."},
        {"code": "o3", "label": "Ozone", "description": "O3."},
        {"code": "so2", "label": "Dioxyde de soufre", "description": "SO2."},
        {"code": "pm2_5", "label": "Particules fines PM2.5", "description": "≤ 2.5 μm."},
        {"code": "pm10", "label": "Particules fines PM10", "description": "≤ 10 μm."},
        {"code": "nh3", "label": "Ammoniac", "description": "NH3."}
    ]
    for entry in data:
        RefIndicator.objects.update_or_create(code=entry["code"], defaults=entry)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_indicators)
    ]
