# Generated by Django 5.1.6 on 2025-07-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_refindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='alert_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=16),
        ),
        migrations.AlterField(
            model_name='alertthreshold',
            name='indicator',
            field=models.ForeignKey(db_column='indicator_code', on_delete=django.db.models.deletion.CASCADE, to='api.refindicator'),
        ),
    ]
