# Generated by Django 5.1.6 on 2025-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alerte_alert_type_alter_alertthreshold_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime_utc', models.DateTimeField()),
                ('aqi', models.IntegerField()),
                ('co', models.FloatField()),
                ('no', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('so2', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('nh3', models.FloatField()),
            ],
            options={
                'db_table': 'air_quality_measurement',
                'indexes': [models.Index(fields=['latitude', 'longitude', 'datetime_utc'], name='air_quality_latitud_1b08a2_idx')],
                'unique_together': {('latitude', 'longitude', 'datetime_utc')},
            },
        ),
    ]
